"""Add initial originating authority data

Revision ID: 0df125363c53
Revises: 4b302c6803fd
Create Date: 2018-02-01 16:00:10.462313

"""

# revision identifiers, used by Alembic.
revision = '0df125363c53'
down_revision = '4b302c6803fd'

from alembic import op
from sqlalchemy import text
from sqlalchemy.schema import Sequence, CreateSequence, DropSequence

authorities = [
    'Bath and North East Somerset Council',
    'Blackburn with Darwen Borough Council',
    'Bedford Borough Council',
    'Birmingham City Council',
    'Bournemouth Borough Council',
    'Brighton and Hove City Council',
    'Barnsley Metropolitan Borough Council',
    'Bolton Metropolitan Borough Council',
    'Blackpool Borough Council',
    'Bracknell Forest Council',
    'City of Bradford Metropolitan District Council',
    'Bristol City Council',
    'Bury Metropolitan Borough Council',
    'Central Bedfordshire Council',
    'Cheshire East Council',
    'Cheshire West and Chester Council',
    'Calderdale Metropolitan Borough Council',
    'Cornwall Council',
    'Coventry City Council',
    'Darlington Borough Council',
    'Doncaster Metropolitan Borough Council',
    'Dudley Metropolitan Borough Council',
    'Durham County Council',
    'East Riding of Yorkshire Council',
    'Gateshead Metropolitan Borough Council',
    'Halton Borough Council',
    'Herefordshire Council',
    'Hartlepool Borough Council',
    'Council of the Isles of Scilly',
    'Isle of Wight Council',
    'Hull City Council',
    'Kirklees Council',
    'Knowsley Metropolitan Borough Council',
    'Leicester City Council',
    'Leeds City Council',
    'Liverpool City Council',
    'Luton Borough Council',
    'Manchester City Council',
    'Middlesbrough Borough Council',
    'Medway Council',
    'Milton Keynes Council',
    'Northumberland County Council',
    'North East Lincolnshire Council',
    'Newcastle City Council',
    'Nottingham City Council',
    'North Lincolnshire Council',
    'North Somerset  Council',
    'North Tyneside Council',
    'Oldham Metropolitan Borough Council',
    'Plymouth City Council',
    'Borough of Poole',
    'Portsmouth City Council',
    'Peterborough City Council',
    'Redcar and Cleveland Borough Council',
    'Rochdale Metropolitan Borough Council',
    'Reading Borough Council',
    'Rotherham Metropolitan Borough Council',
    'Rutland County Council',
    'Sandwell Metropolitan Borough Council',
    'Sefton Metropolitan Borough Council',
    'South Gloucestershire Council',
    'Sheffield City Council',
    'St Helens Council',
    'Shropshire Council',
    'Stockport Metropolitan Borough Council',
    'Salford City Council',
    'Slough Borough Council',
    'Sunderland City Council',
    'Solihull Metropolitan Borough Council',
    'Southend-on-Sea Borough Council',
    'Stoke-on-Trent City Council',
    'Southampton City Council',
    'Stockton-on-Tees Borough Council',
    'South Tyneside Council',
    'Swindon Borough Council',
    'Tameside Metropolitan Borough Council',
    'Telford & Wrekin Council',
    'Thurrock Council',
    'Torbay Council',
    'Trafford Metropolitan Borough Council',
    'West Berkshire Council',
    'Wigan Metropolitan Borough Council',
    'Wiltshire Council',
    'Wakefield Metropolitan District Council',
    'Walsall Metropolitan Borough Council',
    'City of Wolverhampton Council',
    'Royal Borough of Windsor and Maidenhead',
    'Wokingham Borough Council',
    'Wirral Borough Council',
    'Warrington Borough Council',
    'City of York Council',
    'Aylesbury Vale District Council',
    'Chiltern District Council',
    'South Bucks District Council',
    'Wycombe District Council',
    'Cambridge City Council',
    'East Cambridgeshire District Council',
    'Fenland District Council',
    'Huntingdonshire District Council',
    'South Cambridgeshire District Council',
    'Allerdale Borough Council',
    'Barrow-in-Furness Borough Council',
    'Carlisle City Council',
    'Copeland Borough Council',
    'Eden District Council',
    'South Lakeland District Council',
    'Derby City Council',
    'Amber Valley Borough Council',
    'Bolsover District Council',
    'Chesterfield Borough Council',
    'Derbyshire Dales District Council',
    'Erewash Borough Council',
    'High Peak Borough Council',
    'North East Derbyshire District Council',
    'South Derbyshire District Council',
    'East Devon District Council',
    'Exeter City Council',
    'Mid Devon District Council',
    'North Devon District Council',
    'South Hams District Council',
    'Teignbridge District Council',
    'Torridge District Council',
    'West Devon Borough Council',
    'Christchurch Borough Council',
    'East Dorset District Council',
    'North Dorset District Council',
    'Purbeck District Council',
    'West Dorset District Council',
    'Weymouth and Portland Borough Council',
    'Basildon Borough Council',
    'Braintree District Council',
    'Brentwood Borough Council',
    'Castle Point Borough Council',
    'Chelmsford City Council',
    'Colchester Borough Council',
    'Epping Forest District Council',
    'Harlow District Council',
    'Maldon District Council',
    'Rochford District Council',
    'Tendring District Council',
    'Uttlesford District Council',
    'Eastbourne Borough Council',
    'Hastings Borough Council',
    'Lewes District Council',
    'Rother District Council',
    'Wealden District Council',
    'London Borough of Barking and Dagenham',
    'London Borough of Brent',
    'London Borough of Bexley',
    'London Borough of Barnet',
    'London Borough of Bromley',
    'London Borough of Camden',
    'London Borough of Croydon',
    'London Borough of Ealing',
    'London Borough of Enfield',
    'Royal Borough of Greenwich',
    'London Borough of Havering',
    'London Borough of Hackney',
    'London Borough of Hillingdon',
    'London Borough of Hammersmith & Fulham',
    'London Borough of Hounslow',
    'London Borough of Harrow',
    'London Borough of Haringey',
    'London Borough of Islington',
    'Royal Borough of Kensington and Chelsea',
    'Royal Borough of Kingston upon Thames',
    'London Borough of Lambeth',
    'London Borough of Lewisham',
    'London Borough of Merton',
    'London Borough of Newham',
    'London Borough of Redbridge',
    'London Borough of Richmond upon Thames',
    'London Borough of Sutton',
    'London Borough of Southwark',
    'London Borough of Tower Hamlets',
    'London Borough of Waltham Forest',
    'London Borough of Wandsworth',
    'City of Westminster',
    'Cheltenham Borough Council',
    'Cotswold District Council',
    'Forest of Dean District Council',
    'Gloucester City Council',
    'Stroud District Council',
    'Tewkesbury Borough Council',
    'Basingstoke and Deane Borough Council',
    'East Hampshire District Council',
    'Eastleigh Borough Council',
    'Fareham Borough Council',
    'Gosport Borough Council',
    'Hart District Council',
    'Havant Borough Council',
    'New Forest District Council',
    'Rushmoor Borough Council',
    'Test Valley Borough Council',
    'Winchester City Council',
    'Broxbourne Borough Council',
    'Dacorum Borough Council',
    'East Hertfordshire District Council',
    'Hertsmere Borough Council',
    'North Hertfordshire District Council',
    'St Albans City and District Council',
    'Stevenage Borough Council',
    'Three Rivers District Council',
    'Watford Borough Council',
    'Welwyn Hatfield Borough Council',
    'Ashford Borough Council',
    'Canterbury City Council',
    'Dartford Borough Council',
    'Dover District Council',
    'Gravesham Borough Council',
    'Maidstone Borough Council',
    'Sevenoaks District Council',
    'Shepway District Council',
    'Swale Borough Council',
    'Thanet District Council',
    'Tonbridge and Malling Borough Council',
    'Tunbridge Wells Borough Council',
    'Burnley Borough Council',
    'Chorley Borough Council',
    'Fylde Borough Council',
    'Hyndburn Borough Council',
    'Lancaster City Council',
    'Pendle Borough Council',
    'Preston City Council',
    'Ribble Valley Borough Council',
    'Rossendale Borough Council',
    'South Ribble Borough Council',
    'West Lancashire Borough Council',
    'Wyre Borough Council',
    'Blaby District Council',
    'Charnwood Borough Council',
    'Harborough District Council',
    'Hinckley and Bosworth Borough Council',
    'Melton Borough Council',
    'North West Leicestershire District Council',
    'Oadby and Wigston Borough Council',
    'Boston Borough Council',
    'East Lindsey District Council',
    'City of Lincoln Council',
    'North Kesteven District Council',
    'South Holland District Council',
    'South Kesteven District Council',
    'West Lindsey District Council',
    'Breckland District Council',
    'Broadland District Council',
    'Great Yarmouth Borough Council',
    'North Norfolk District Council',
    'Norwich City Council',
    'South Norfolk District Council',
    'Corby Borough Council',
    'Daventry District Council',
    'East Northamptonshire Council',
    'Kettering Borough Council',
    'Northampton Borough Council',
    'South Northamptonshire Council',
    'Wellingborough Borough Council',
    'Ashfield District Council',
    'Bassetlaw District Council',
    'Broxtowe Borough Council',
    'Gedling Borough Council',
    'Mansfield District Council',
    'Newark and Sherwood District Council',
    'Rushcliffe Borough Council',
    'Craven District Council',
    'Hambleton District Council',
    'Harrogate Borough Council',
    'Richmondshire District Council',
    'Ryedale District Council',
    'Scarborough Borough Council',
    'Selby District Council',
    'Cherwell District Council',
    'Oxford City Council',
    'South Oxfordshire District Council',
    'Vale of White Horse District Council',
    'West Oxfordshire District Council',
    'Babergh District Council',
    'Forest Heath District Council',
    'Ipswich Borough Council',
    'Mid Suffolk District Council',
    'St Edmundsbury Borough Council',
    'Suffolk Coastal District Council',
    'Waveney District Council',
    'Mendip District Council',
    'Sedgemoor District Council',
    'South Somerset District Council',
    'Taunton Deane Borough Council',
    'West Somerset District Council',
    'Elmbridge Borough Council',
    'Epsom and Ewell Borough Council',
    'Guildford Borough Council',
    'Mole Valley District Council',
    'Reigate and Banstead Borough Council',
    'Runnymede Borough Council',
    'Spelthorne Borough Council',
    'Surrey Heath Borough Council',
    'Tandridge District Council',
    'Waverley Borough Council',
    'Woking Borough Council',
    'Cannock Chase District Council',
    'East Staffordshire Borough Council',
    'Lichfield District Council',
    'Newcastle-under-Lyme Borough Council',
    'South Staffordshire Council',
    'Stafford Borough Council',
    'Staffordshire Moorlands District Council',
    'Tamworth Borough Council',
    'North Warwickshire Borough Council',
    'Nuneaton and Bedworth Borough Council',
    'Rugby Borough Council',
    'Stratford-on-Avon District Council',
    'Warwick District Council',
    'Bromsgrove District Council',
    'Malvern Hills District Council',
    'Redditch Borough Council',
    'Worcester City Council',
    'Wychavon District Council',
    'Wyre Forest District Council',
    'Adur District Council',
    'Arun District Council',
    'Chichester District Council',
    'Crawley Borough Council',
    'Horsham District Council',
    'Mid Sussex District Council',
    'Worthing Borough Council',
    'City of London Corporation',
    'Borough Council of King\'s Lynn and West Norfolk'
]

def upgrade():
    op.execute(CreateSequence(Sequence('originating_authorities_id_seq')))
    op.alter_column('originating_authorities', 'id', server_default=text("nextval('originating_authorities_id_seq'::regclass)"))

    for authority in authorities:
        query = "DO $$ BEGIN IF NOT EXISTS (SELECT FROM originating_authorities WHERE name = '{0}') THEN INSERT INTO originating_authorities " \
                "(name) VALUES ('{0}'); END IF; END $$;".format(authority.replace("\'", "\'\'"))
        op.execute(query)


def downgrade():
    query = 'DELETE FROM originating_authorities WHERE name IN ({});'.format(', '.join('\'' + authority.replace("\'", "\'\'") + '\'' for authority in authorities))
    op.execute(query)

    op.alter_column('originating_authorities', 'id', server_default=None)
    op.execute(DropSequence(Sequence('originating_authorities_id_seq')))
