"""Load authority boundaries shapefile

Revision ID: f4560bd06da5
Revises: 99adc3ab1073
Create Date: 2018-02-05 09:47:52.472482

"""

# revision identifiers, used by Alembic.
revision = 'f4560bd06da5'
down_revision = '99adc3ab1073'

from alembic import op
import sqlalchemy as sa
import os
from local_authority_api import config
from local_authority_api.alembic_utils.shapefile_loader import load_shapefile

boundary_names = [
    'Adur District',
    'Allerdale District (B)',
    'Amber Valley District (B)',
    'Arun District',
    'Ashfield District',
    'Ashford District (B)',
    'Aylesbury Vale District',
    'Babergh District',
    'Barnsley District (B)',
    'Barrow-in-Furness District (B)',
    'Basildon District (B)',
    'Basingstoke and Deane District (B)',
    'Bassetlaw District',
    'Bath and North East Somerset',
    'Bedford (B)',
    'Birmingham District (B)',
    'Blaby District',
    'Blackburn with Darwen (B)',
    'Blackpool (B)',
    'Bolsover District',
    'Bolton District (B)',
    'Boston District (B)',
    'Bournemouth (B)',
    'Bracknell Forest (B)',
    'Bradford District (B)',
    'Braintree District',
    'Breckland District',
    'Brentwood District (B)',
    'The City of Brighton and Hove (B)',
    'City of Bristol (B)',
    'Broadland District',
    'Bromsgrove District',
    'Broxbourne District (B)',
    'Broxtowe District (B)',
    'Burnley District (B)',
    'Bury District (B)',
    'Calderdale District (B)',
    'Cambridge District (B)',
    'Cannock Chase District',
    'Canterbury District (B)',
    'Carlisle District (B)',
    'Castle Point District (B)',
    'Central Bedfordshire',
    'Charnwood District (B)',
    'Chelmsford District (B)',
    'Cheltenham District (B)',
    'Cherwell District',
    'Cheshire East (B)',
    'Cheshire West and Chester (B)',
    'Chesterfield District (B)',
    'Chichester District',
    'Chiltern District',
    'Chorley District (B)',
    'Christchurch District (B)',
    'City and County of the City of London',
    'City of Westminster London Boro',
    'Colchester District (B)',
    'Copeland District (B)',
    'Corby District (B)',
    'Cornwall',
    'Cotswold District',
    'County Durham',
    'Coventry District (B)',
    'Craven District',
    'Crawley District (B)',
    'Dacorum District (B)',
    'Darlington (B)',
    'Dartford District (B)',
    'Daventry District',
    'City of Derby (B)',
    'Derbyshire Dales District',
    'Doncaster District (B)',
    'Dover District',
    'Dudley District (B)',
    'East Cambridgeshire District',
    'East Devon District',
    'East Dorset District',
    'East Hampshire District',
    'East Hertfordshire District',
    'East Lindsey District',
    'East Northamptonshire District',
    'East Riding of Yorkshire',
    'East Staffordshire District (B)',
    'Eastbourne District (B)',
    'Eastleigh District (B)',
    'Eden District',
    'Elmbridge District (B)',
    'Epping Forest District',
    'Epsom and Ewell District (B)',
    'Erewash District (B)',
    'Exeter District (B)',
    'Fareham District (B)',
    'Fenland District',
    'Forest Heath District',
    'Forest of Dean District',
    'Fylde District (B)',
    'Gateshead District (B)',
    'Gedling District (B)',
    'Gloucester District (B)',
    'Gosport District (B)',
    'Gravesham District (B)',
    'Great Yarmouth District (B)',
    'Guildford District (B)',
    'Halton (B)',
    'Hambleton District',
    'Harborough District',
    'Harlow District',
    'Harrogate District (B)',
    'Hart District',
    'Hartlepool (B)',
    'Hastings District (B)',
    'Havant District (B)',
    'County of Herefordshire',
    'Hertsmere District (B)',
    'High Peak District (B)',
    'Hinckley and Bosworth District (B)',
    'Horsham District',
    'Huntingdonshire District',
    'Hyndburn District (B)',
    'Ipswich District (B)',
    'Isle of Wight',
    'Isles of Scilly',
    'Kettering District (B)',
    'King\'s Lynn and West Norfolk District (B)',
    'City of Kingston upon Hull (B)',
    'Kirklees District (B)',
    'Knowsley District (B)',
    'Lancaster District (B)',
    'Leeds District (B)',
    'City of Leicester (B)',
    'Lewes District',
    'Lichfield District',
    'Lincoln District (B)',
    'Liverpool District (B)',
    'Barking and Dagenham London Boro',
    'Barnet London Boro',
    'Bexley London Boro',
    'Brent London Boro',
    'Bromley London Boro',
    'Camden London Boro',
    'Croydon London Boro',
    'Ealing London Boro',
    'Enfield London Boro',
    'Greenwich London Boro',
    'Hackney London Boro',
    'Hammersmith and Fulham London Boro',
    'Haringey London Boro',
    'Harrow London Boro',
    'Havering London Boro',
    'Hillingdon London Boro',
    'Hounslow London Boro',
    'Islington London Boro',
    'Lambeth London Boro',
    'Lewisham London Boro',
    'Merton London Boro',
    'Newham London Boro',
    'Redbridge London Boro',
    'Richmond upon Thames London Boro',
    'Southwark London Boro',
    'Sutton London Boro',
    'Tower Hamlets London Boro',
    'Waltham Forest London Boro',
    'Wandsworth London Boro',
    'Luton (B)',
    'Maidstone District (B)',
    'Maldon District (B)',
    'Malvern Hills District',
    'Manchester District (B)',
    'Mansfield District',
    'Medway (B)',
    'Melton District (B)',
    'Mendip District',
    'Mid Devon District',
    'Mid Suffolk District',
    'Middlesbrough (B)',
    'Mid Sussex District',
    'Milton Keynes (B)',
    'Mole Valley District',
    'New Forest District',
    'Newark and Sherwood District',
    'Newcastle upon Tyne District (B)',
    'Newcastle-under-Lyme District (B)',
    'North Devon District',
    'North Dorset District',
    'North East Derbyshire District',
    'North East Lincolnshire (B)',
    'North Hertfordshire District',
    'North Kesteven District',
    'North Lincolnshire (B)',
    'North Norfolk District',
    'North Somerset',
    'North Tyneside District (B)',
    'North Warwickshire District (B)',
    'North West Leicestershire District',
    'Northampton District (B)',
    'Northumberland',
    'Norwich District (B)',
    'City of Nottingham (B)',
    'Nuneaton and Bedworth District (B)',
    'Oadby and Wigston District (B)',
    'Oldham District (B)',
    'Oxford District (B)',
    'Pendle District (B)',
    'City of Peterborough (B)',
    'City of Plymouth (B)',
    'Poole (B)',
    'City of Portsmouth (B)',
    'Preston District (B)',
    'Purbeck District',
    'Reading (B)',
    'Redcar and Cleveland (B)',
    'Redditch District (B)',
    'Reigate and Banstead District (B)',
    'Ribble Valley District (B)',
    'Richmondshire District',
    'Rochdale District (B)',
    'Rochford District',
    'Rossendale District (B)',
    'Rother District',
    'Rotherham District (B)',
    'Kensington and Chelsea London Boro',
    'Kingston upon Thames London Boro',
    'Rugby District (B)',
    'Runnymede District (B)',
    'Rushcliffe District (B)',
    'Rushmoor District (B)',
    'Rutland',
    'Ryedale District',
    'Salford District (B)',
    'Sandwell District (B)',
    'Scarborough District (B)',
    'Sedgemoor District',
    'Sefton District (B)',
    'Selby District',
    'Sevenoaks District',
    'Sheffield District (B)',
    'Shepway District',
    'Shropshire',
    'Slough (B)',
    'Solihull District (B)',
    'South Bucks District',
    'South Cambridgeshire District',
    'South Derbyshire District',
    'South Gloucestershire',
    'South Hams District',
    'South Holland District',
    'South Kesteven District',
    'South Lakeland District',
    'South Norfolk District',
    'South Northamptonshire District',
    'South Oxfordshire District',
    'South Ribble District (B)',
    'South Somerset District',
    'South Staffordshire District',
    'South Tyneside District (B)',
    'City of Southampton (B)',
    'Southend-on-Sea (B)',
    'Spelthorne District (B)',
    'St. Albans District (B)',
    'St. Edmundsbury District (B)',
    'St. Helens District (B)',
    'Stafford District (B)',
    'Staffordshire Moorlands District',
    'Stevenage District (B)',
    'Stockport District (B)',
    'Stockton-on-Tees (B)',
    'City of Stoke-on-Trent (B)',
    'Stratford-on-Avon District',
    'Stroud District',
    'Suffolk Coastal District',
    'Sunderland District (B)',
    'Surrey Heath District (B)',
    'Swale District (B)',
    'Swindon (B)',
    'Tameside District (B)',
    'Tamworth District (B)',
    'Tandridge District',
    'Taunton Deane District (B)',
    'Teignbridge District',
    'Telford and Wrekin (B)',
    'Tendring District',
    'Test Valley District',
    'Tewkesbury District (B)',
    'Thanet District',
    'Three Rivers District',
    'Thurrock (B)',
    'Tonbridge and Malling District (B)',
    'Torbay (B)',
    'Torridge District',
    'Trafford District (B)',
    'Tunbridge Wells District (B)',
    'Uttlesford District',
    'Vale of White Horse District',
    'Wakefield District (B)',
    'Walsall District (B)',
    'Warrington (B)',
    'Warwick District',
    'Watford District (B)',
    'Waveney District',
    'Waverley District (B)',
    'Wealden District',
    'Wellingborough District (B)',
    'Welwyn Hatfield District (B)',
    'West Berkshire',
    'West Devon District (B)',
    'West Dorset District',
    'West Lancashire District (B)',
    'West Lindsey District',
    'West Oxfordshire District',
    'West Somerset District',
    'Weymouth and Portland District (B)',
    'Wigan District (B)',
    'Wiltshire',
    'Winchester District (B)',
    'Windsor and Maidenhead (B)',
    'Wirral District (B)',
    'Woking District (B)',
    'Wokingham (B)',
    'City of Wolverhampton District (B)',
    'Worcester District (B)',
    'Worthing District (B)',
    'Wychavon District',
    'Wycombe District',
    'Wyre District (B)',
    'Wyre Forest District',
    'York (B)',
    'Castell-nedd Port Talbot - Neath Port Talbot',
    'Clackmannanshire',
    'Conwy - Conwy',
    'Abertawe - Swansea',
    'Angus',
    'Blaenau Gwent - Blaenau Gwent',
    'Bro Morgannwg - the Vale of Glamorgan',
    'Caerffili - Caerphilly',
    'Casnewydd - Newport',
    'Dundee City',
    'East Ayrshire',
    'East Dunbartonshire',
    'East Renfrewshire',
    'Falkirk',
    'Glasgow City',
    'Inverclyde',
    'Merthyr Tudful - Merthyr Tydfil',
    'Midlothian',
    'North Lanarkshire',
    'Pen-y-bont ar Ogwr - Bridgend',
    'Perth and Kinross',
    'Powys - Powys',
    'Renfrewshire',
    'Rhondda Cynon Taf - Rhondda Cynon Taf',
    'Scottish Borders',
    'Sir Ddinbych - Denbighshire',
    'Sir Gaerfyrddin - Carmarthenshire',
    'Sir y Fflint - Flintshire',
    'South Lanarkshire',
    'Stirling',
    'Tor-faen - Torfaen',
    'West Dunbartonshire',
    'West Lothian',
    'Wrecsam - Wrexham',
    'Sir Ynys Mon - Isle of Anglesey',
    'Gwynedd - Gwynedd',
    'Caerdydd - Cardiff',
    'Sir Ceredigion - Ceredigion',
    'Sir Fynwy - Monmouthshire',
    'Sir Benfro - Pembrokeshire',
    'Highland',
    'Moray',
    'Orkney Islands',
    'Na h-Eileanan an Iar',
    'Argyll and Bute',
    'Aberdeenshire',
    'Fife',
    'Aberdeen City',
    'City of Edinburgh',
    'East Lothian',
    'Shetland Islands',
    'North Ayrshire',
    'Dumfries and Galloway',
    'South Ayrshire'
]

def upgrade():
    # Only insert boundary data if the boundary table is empty
    query = "SELECT name FROM boundaries LIMIT 1;"
    conn = op.get_bind()
    result = conn.exec_driver_sql(query).fetchall()
    if not result:
        load_shapefile(op, "./fragments/data/f4560bd06da5_district_borough_unitary_region.shp", "public.boundaries")


def downgrade():
    query = 'DELETE FROM boundaries WHERE name IN ({});'.format(', '.join('\'' + boundary_name.replace("\'", "\'\'") + '\'' for boundary_name in boundary_names))
    op.execute(query)
